# Generated by Django 2.2.2 on 2019-07-01 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20190630_1631'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='login',
            new_name='logindata',
        ),
    ]
