# Generated by Django 2.2.2 on 2019-07-01 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20190701_0943'),
    ]

    operations = [
        migrations.CreateModel(
            name='photodata',
            fields=[
                ('email', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('photo', models.CharField(max_length=100)),
            ],
        ),
    ]
