# Generated by Django 2.2.2 on 2019-07-01 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_photodata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photodata',
            name='photo',
            field=models.TextField(max_length=100),
        ),
    ]
