# Generated by Django 2.2.2 on 2019-07-01 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_photodata_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='photodata',
            name='photo',
            field=models.TextField(default='no file', max_length=1000),
        ),
    ]
