# Generated by Django 2.2.2 on 2019-07-02 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_photodata_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='admindata',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100, primary_key=True, serialize=False)),
                ('Contact', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='employee',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('ID', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100, primary_key=True, serialize=False)),
                ('contact', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameModel(
            old_name='registration',
            new_name='student',
        ),
    ]
