# Generated by Django 2.2.2 on 2019-07-02 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20190702_0820'),
    ]

    operations = [
        migrations.CreateModel(
            name='requests',
            fields=[
                ('email', models.EmailField(max_length=100, primary_key=True, serialize=False)),
                ('message', models.EmailField(max_length=1000)),
            ],
        ),
        migrations.RenameField(
            model_name='student',
            old_name='branch',
            new_name='standard',
        ),
    ]
