# Generated by Django 2.2.2 on 2019-07-02 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20190702_1858'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requests',
            name='new_email',
        ),
    ]
