# Generated by Django 2.2.2 on 2019-07-03 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_remove_requests_new_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='fees',
            fields=[
                ('email', models.EmailField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('standard', models.CharField(max_length=100)),
                ('roll_number', models.CharField(max_length=100)),
                ('fees_due', models.CharField(max_length=100)),
            ],
        ),
    ]
