# Generated by Django 2.2.2 on 2019-07-03 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_fees'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fees',
            name='fees_due',
            field=models.IntegerField(),
        ),
    ]
