# Generated by Django 2.2.2 on 2019-07-03 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20190703_0658'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fees',
            name='fees_due',
        ),
    ]
