# Generated by Django 2.2.2 on 2019-07-03 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_fees_fees_due'),
    ]

    operations = [
        migrations.CreateModel(
            name='phadmin',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100, primary_key=True, serialize=False)),
                ('photo', models.TextField(default='no file', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='phemployee',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100, primary_key=True, serialize=False)),
                ('photo', models.TextField(default='no file', max_length=1000)),
                ('ID', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='phstudent',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('standard', models.CharField(max_length=100)),
                ('roll_number', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100, primary_key=True, serialize=False)),
                ('photo', models.TextField(default='no file', max_length=1000)),
            ],
        ),
        migrations.RenameField(
            model_name='admindata',
            old_name='Contact',
            new_name='contact',
        ),
    ]
