# Generated by Django 2.2.2 on 2019-07-03 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_auto_20190703_2206'),
    ]

    operations = [
        migrations.DeleteModel(
            name='phadmin',
        ),
        migrations.DeleteModel(
            name='phemployee',
        ),
        migrations.DeleteModel(
            name='phstudent',
        ),
    ]
