# Generated by Django 2.2.2 on 2019-07-04 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_auto_20190703_2233'),
    ]

    operations = [
        migrations.AddField(
            model_name='fees',
            name='photo',
            field=models.TextField(default='no file', max_length=1000),
        ),
    ]
