# Generated by Django 2.2.2 on 2019-07-04 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_fees_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fees',
            name='photo',
            field=models.TextField(default='no', max_length=1000),
        ),
    ]
